# Boletín: 10 exercicios de Introdución a Python 
Este boletín acompaña o caderno de **00.python_intro.ipynb**.
Cada exercicio inclúe un **enunciado** e logo unha **cela baleira** para a túa resolución.


## 1) Sintaxe básica: indentación, variables e comentarios
**Obxectivo:** practicar indentación e estrutura básica de bloques.

**Tarefas:**
- A. Crea unha variable `nota` e asigna un número entre 0 e 10.
- B. Usa `if/elif/else` para imprimir unha mensaxe segundo a cualificación (suspenso/aprobado/notable/sobresaínte).
- C. Engade **un comentario de liña** explicando que fai o bloque condicional.

In [31]:
# Escribe aquí a túa solución para o Exercicio 1
# A:
nota = 1

# B:
if nota < 5: # C. Se a nota é inferior a 5, amosa "suspenso"
    mensaxe = "suspenso"
elif nota < 7: # C. Se a nota é inferior a 7, amosa "suficiente"
    mensaxe = "suficiente"
elif nota < 9: # C. Se a nota é inferior a 9, amosa "notable"
    mensaxe = "notable"
else: # C. En caso contrario, amosa "sobresaínte"
    mensaxe = "sobresaínte"

print(f"A nota é {mensaxe}")

    

A nota é suspenso


## 2) Tipos simples e operadores (+ casting)
**Obxectivo:** traballar con `int`, `float`, `str`, `bool`, conversións e operadores.

**Tarefas:**
- A. Define `ancho` e `alto` dun rectángulo (enteiro ou real) e calcula **área** e **perímetro**.
- B. Mostra o resultado cunha *f-string* con 2 decimais.
- C. Comproba se é maior a área que o perímetro e amosa o valor booleano.
- D. Fai 2 exemplos de *casting* (p.ex. `int('7')`, `float('3.5')`).


In [36]:
# Exercicio 2: solución aquí
# A
ancho = float('4')
alto = 3
area = ancho*alto
perimetro = 2*ancho+2*alto

# B
print(f"A área é {area:.2f} e o perímetro é {perimetro:.2f} ")

# C
comp = area> perimetro
print (f"O resultado da comparación é {comp}")

# D
num = int('7')
print (num)

num2 = float('3.5')
print (num2)

A área é 12.00 e o perímetro é 14.00 
O resultado da comparación é False
7
3.5


## 3) Strings: slicing, métodos e formato
**Obxectivo:** manipular cadeas de texto.

**Tarefas:**
- A. Toma `nome_completo = 'ana maria perez'` e convérteo a `Ana Maria Perez` (podes dividir por espazos e capitalizar cada parte).
- B. Xera as iniciais no formato `A.M.P.`


In [11]:
# Exercicio 3: solución aquí
# A: 
nome_completo='ana maria perez'
nome, ap1, ap2 = nome_completo.split()
print (f"{nome.capitalize()} {ap1.capitalize()}")

# B:
iniciais = f"{nome[0].upper()}.{ap1[0].upper()}.{ap2[0].upper()}."
print(iniciais)


Ana Maria
A.M.P.


## 4) Estruturas complexas: listas, tuplas, sets, dicts e array
**Obxectivo:** practicar operacións frecuentes con coleccións.

**Tarefas:**
- A. Dende `nomes = ['Ana','Ana','Brais','Lucia','Brais']`, crea un `set` para deduplicar.
- B. Crea `idades = {'Ana':20, 'Brais':30}`; engade outra persoa, actualiza unha idade e elimina outra **sen erro** se non existe.
- C. Xera `idades_meses` por comprensión, multiplicando cada idade * 12.
- D. Usa `array('i', ...)` para gardar 5 enteiros e transforma a lista con `.tolist()`.


In [45]:
# Exercicio 4: solución aquí
# A
nomes = ['Ana','Ana','Brais','Lucia','Brais']
for n in nomes: 
    print (n)
nomes_set = set(nomes)
print(nomes_set)

# B
idades = {'Ana':20, 'Brais':30}
idades['Adri']=41

idades['Brais']+=1
print(idades)
idades.pop('Adri')
idades.pop('Elena', None)
print(idades)

# C
idades_meses = {nome: idade*12 for nome,idade in idades.items()}
print (idades_meses)

# D
from array import array
a = array('i', [1,2,3,4,5])
print(a.tolist())

Ana
Ana
Brais
Lucia
Brais
{'Brais', 'Lucia', 'Ana'}
{'Ana': 20, 'Brais': 31, 'Adri': 41}
{'Ana': 20, 'Brais': 31}
{'Ana': 240, 'Brais': 372}
[1, 2, 3, 4, 5]


## 5) Control de fluxo: if/elif/else, match, while, for
**Obxectivo:** dominar condicións e bucles.

**Tarefas (podes facelas en funcións ou directamente):**
- A. Crea unha variable idade e asígnalle un valor. Escribe un bloque if/else que comprobe se é menor que 18, imprimindo "Non podes beber alcol" se é o caso ou "Adiante, pero con moderación" en caso contrario.
- B. Usa **`match`** para interpretar un comando tipo `('op','a','b')`, onde `op` pode ser `'sumar'`, `'restar'`, `'mul'`, `'div'` (xestiona división por cero).
- C. Escribe un **`while`** que lea cadeas con números ata que chegue `'fin'` (podes simular cunha lista) e devolva a suma total.
- D. Fai un **`for`** con *list comprehension* para obter todos os múltiplos de 3 entre 0 e 30.


In [ ]:
# Exercicio 5: solución aquí
# a.
idade = 16
if idade < 18:
    print ("Non podes beber alcol")
else:
    print ("Adiante, pero con moderación")
op = 'sumar'
a = 4
b = 5
match op:
    case 'sumar':
        print (f"{a+b}")
    case 'restar':
        print (f"{a-b}")
    case 'multiplicar':
        print (f"{a*b}")
    case 'dividir':
        if (b == 0):
            print("Erro: non se pode dividir por 0")
        else:
            print (f"{a/b}")
    case _:
        print ("Comando descoñecido")

multi3 = [n for n in range(31) if n % 3 == 0]
print (multi3)


Non podes beber alcol
9
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


## 6) Funcións: parámetros, lambda, decoradores e range
**Obxectivo:** definir e compoñer funcións.

**Tarefas:**
- A. Implementa `media(*nums, arredondar=None)`; se `arredondar` é un enteiro, redondea o resultado a ese número de decimais.
- B. Crea un **decorador** `log` que imprima o nome da función e os argumentos antes de executala; proba con unha función simple.
- C. Ordena unha lista de palabras pola súa lonxitude con `sorted(..., key=lambda s: len(s))`.
- D. Xera unha lista cos múltiplos de 3 entre 0 e 30 usando `range`.


3.2
[LOG] chamando a sumar con (7, 5) {}
[LOG] sumar devolveu 12


12

In [ ]:
# Exercicio 6: solución aquí

#A

def media (*nums, arredondar=None):
    acc = 0
    for num in nums:
        acc+=num
    res = acc/len(nums)
    if isinstance(arredondar,int):
        return round(res,arredondar)
    return res
print (media(1,2,3,7,arredondar=1))
#B
def log(func):
    def envoltura(*args,**kwargs):
        # Antes de executar a función orixinal:
        print(f"[LOG] chamando a {func.__name__} con {args} {kwargs}")
        
        # Executamos a función orixinal con eses mesmos argumentos:
        resultado = func(*args, **kwargs)
        
        # Despois de executar, rexistramos o resultado:
        print(f"[LOG] {func.__name__} devolveu {resultado}")
        return resultado
    return envoltura

@log
def sumar (a, b):
    return a+b

sumar (7,5)


# C
lp = ["hola", "cabeza", "de", "membrillo"]
lps = sorted(lp, key=lambda s:len(s))
print (lps)

# D
print (list(range(0,31,3)))

media: 1.5
[LOG] chamando a saludar con ('adri',) {}
hola, adri
['de', 'hola', 'cabeza', 'membrillo']
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


## 7) Entrada e saída de usuario: `print` e `input`
**Obxectivo:** practicar I/O básica.

**Tarefas:**
- A. Escribe un pequeno diálogo que pregunte polo **nome** e pola **idade**, e despois imprima `Ola, <nome>! Tes <idade> anos.`
- B. Emprega parámetro(s) de `print` como `sep` e/ou `end` nalgún caso.
  
*(Se traballas nun notebook, lembra que `input()` detén a execución ata introducir datos)*


In [29]:
# Exercicio 7: solución aquí
# A
print ("Cal é o teu nome?")
nome = input()
print ("Cal é a túa idade?")
idade = input()
print(f"Ola, {nome}, tes {idade} anos")

# B
print ("A", "B", "C", sep="->", end="\n\n")


Cal é o teu nome?


 adri


Cal é a túa idade?


 41


Ola, adri, tes 41 anos
A->B->C



## 8) Orientación a obxectos: clases, herdanza, polimorfismo
**Obxectivo:** crear clases e empregar herdanza básica.

**Tarefas:**
- A. Define `animal(nome)` cun método `falar()` e representación amigable (ex. con `__str__`).
- B. Define as subclases `can` e `gato` que erdan de `animal`.
  - Sobreescriben o método `falar()` para imprimir o son típico de cada animal (*"guau"* e *"miau"*.
- C. Clase `caixa` con encapsulamento.
  - Atributo interno _items (enteiro) inicializable no constructor.
  - Propiedade de só lectura items para consultar a cantidade actual.
  - Métodos:
    - `engadir(n=1)`: incrementa `_items`; **erro** se `n<=0`
    - `retirar(n=1)`: decremeta `_items`; **erro** se `n<=0` ou se supera os elementos dispoñibles.
- D. Uso de ambas clases:
  - Crea unha lista con `Animal("Bicho")`, `Can("Luna")` e `Gato("Sasuke")`.
  - Recorre a lista e imprime o resultado de `falar()` de cada un (debe chamarse á versión adecuada segundo o tipo).
  - Crea unha `Caixa` con valor inicial 2; imprime `items`, chama a `engadir()` e logo a `retirar(2)`. Finalmente, imprime de novo `items`.

In [2]:
# Exercicio 8: solución aquí
# A
class Animal:
    def __init__(self, nome: str) -> None:
        self.nome = nome
    def falar(self):
        return "..."
    def __str__(self):
        return f"{self.nome}: {self.falar()}"

# B
class Can(Animal):
    def falar(self):
        return "guau"

class Gato(Animal):
    def falar(self):
        return "miau"


# C
class Caixa:
    def __init__(self, items:int):
        self._items = items
    def items(self):
        return self._items
    def engadir(self, n=1):
        if n <= 0:
            raise ValueError("Debes engadir un número positivo.")
        self._items+=n
    def retirar(self, n=1):
        if n <= 0:
            raise ValueError("Debes retirar un número positivo.")
        if n > self._items:
            raise ValueError("Debes retirar un número positivo.")
        self._items-=n
# D 
lista = [Animal("Bicho"), Can("Luna"), Gato("Sasuke")]
for a in lista:
    print (a)

c = Caixa(2)
print (f"items: {c.items()}")
c.retirar(1)
print (f"items: {c.items()}")

    

Bicho: ...
Luna: guau
Sasuke: miau
items: 2
items: 1


## 9) Módulos de Python: datetime, math, json, re
**Obxectivo:** usar a libraría estándar.

**Tarefas:**
- A. `datetime`: imprime a data/hora actual en formato `YYYY-MM-DD HH:MM`.
- B. `math`: calcula √2 con 5 decimais.
- C. `json`: serializa un dicionario sinxelo a cadea e recupérao a obxecto Python.
- D. `re`: valida de forma sinxela un código postal (5 díxitos).


In [8]:
# Exercicio 9: solución aquí
# A.

from datetime import datetime, timedelta, date
agora = datetime.now()
print (agora.strftime("%Y-%m-%d %H:%M"))

#B.
import math
print (f"{math.sqrt(2):.5f}")

#C.
import json
datos = {"nome": "Ana", "idade": 20}
s = json.dumps(datos)
print(s)
print(json.loads(s))

#D.
import re
texto = "32003"
m = re.search(r"[\d]{5}", texto)

if m:
    print ("Código correcto")
else:
    print ("O código debe conter 5 díxitos.")

2025-09-29 06:48
1.41421
{"nome": "Ana", "idade": 20}
{'nome': 'Ana', 'idade': 20}
Código correcto


## 10) NumPy: creación, indexación, broadcasting, estatística e álxebra
**Obxectivo:** practicar vectores e matrices con NumPy.

**Tarefas:**
- A. Crea `a = np.arange(12).reshape(3,4)` e extrae: elemento (1,2), primeira fila, última columna e a submatriz `[0:2, 1:4]`.
- B. Define `v = np.array([1,0,1,0])` e suma a `a` mediante **broadcasting**.
- C. Xera unha matriz aleatoria `r` (3x4) con semente fixa, calcula media total, desviación, máximos por columna e mínimos por fila.
- D. Resolve o sistema `A x = b` con `np.linalg.solve` para `A=[[3,1],[2,4]]` e `b=[5,6]`.


In [55]:
import numpy as np
# Exercicio 10: solución aquí
# A:
a = np.arange(12).reshape(3,4)
print(a)
print (f"elemento(1,2): {a[1,2]}")
print (f"primeira fila: {a[0,:]}")
print(f"última columna: {a[:,-1]}")
print(f"submatriz:{a[0:2, 1:4]}")
# B:
v = np.array([1,0,1,0])
print(f"Broadcasting a+v:{a+v}")

# C:
np.random.seed(45)
m = np.random.rand(3,4)
print(m)

print(f"Media: {m.mean()}")
print(f"Desviación: {m.std()}")
print(f"máx por filas:{m.max(axis=1)}")
print(f"mín por columnas:{m.min(axis=0)}")

# D:
A= np.array([[3,1],[2,4]])
b = np.array([5,6])
sol = np.linalg.solve (A,b)

print(f"Solución: {sol}")



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
elemento(1,2): 6
primeira fila: [0 1 2 3]
última columna: [ 3  7 11]
submatriz:[[1 2 3]
 [5 6 7]]
Broadcasting a+v:[[ 1  1  3  3]
 [ 5  5  7  7]
 [ 9  9 11 11]]
[[0.98901151 0.54954473 0.2814473  0.07728957]
 [0.4444695  0.47280797 0.048522   0.16332445]
 [0.11595071 0.62739168 0.85618205 0.65010242]]
Media: 0.4396703239235092
Desviación: 0.29699677816121334
máx por filas:[0.98901151 0.47280797 0.85618205]
mín por columnas:[0.11595071 0.47280797 0.048522   0.07728957]
Solución: [1.4 0.8]
