# introdución a python — caderno de exercicios

Formato **exercicios**: antes de cada cela de código tes as indicacións claras. Este caderno inclúe **solucións** (para uso do/a docente), que podes eliminar antes de repartir.

> Suxestión: executa en orde. Fórmate o hábito de **ler, predicir, programar e comprobar**.

### guía rápida
- cada exercicio trae unha cela **código do alumnado** baleira ou con esqueleto.
- a continuación tes a **solución**. recomenda ocultala ao alumnado.
- incluímos algúns `assert` para auto-comprobar.

## 1) variables e tipos de datos
Obxectivo: crear variables, inspeccionar tipos e facer conversións.

**exercicio 1.1 — crear variables simples**

Crea as variables:
- `idade` (entero), `altura` (float), `aprobado` (boolean), `nome` (string) e `nada` (`None`).
Logo, mostra o tipo de cada unha usando `type(...)`.

In [2]:
#código do alumnado
idade = 17
altura = 1.9
aprobado = False
nome = "Adrián"
nada = None
type(idade), type(altura), type(aprobado), type(nada), type(nome)

(int, float, bool, NoneType, str)

**exercicio 1.2 — conversións (casting)**

Fai as seguintes conversións e comproba os resultados:
- `int(3.9)`, `float(10)`, `str(123)`, `bool(0)`, `bool(42)`.

In [4]:
# código do alumnado
# int(3.9), float(10), str(123), bool(0), bool(42)
print (int(3.9))
print (float(10))
print (str(123))
print (bool(0))
print (bool(42))


3
10.0
123
False
True


**exercicio 1.3 — media de dúas variables**

Define `a` (int) e `b` (float) e calcula a súa media. Usa parénteses para controlar a orde.

In [7]:
a = 4
b = float(7)
media = (a+b)/2

print(f"media = {media}")
print (type(media))

media = 5.5
<class 'float'>


## 2) operadores e expresións
Obxectivo: practicar aritmética, comparacións e lóxica.

**exercicio 2.1 — operacións aritméticas**

Calcula: suma, resta, produto, división exacta `/`, división enteira `//`, módulo `%` e potencia `**` para algúns números de exemplo.

In [8]:
a = 15
b= 7

suma = a+b
resta = a-b
produto = a*b
divi = a/b
div_ent = a//b
modulo = a%b
pot = a**b

print(suma, resta, produto, divi, div_ent, modulo, pot)

22 8 105 2.142857142857143 2 1 170859375


**exercicio 2.2 — comparacións e lóxica**

Dadas `x=5` e `y=9`, avalía as seguintes expresións lóxicas:
- ¿x é menor que y?
- ¿x -e maior que 0 e menor que y?
- ¿x -e menor que 0 ou menor que y?
- ¿x non é menor que 0 e x menor que y?
Emprega comparacións e operadores lóxicos: `and`, `or`, `not`.

In [ ]:
# código do alumnado

x,y = 5,9
x<y and not(x<0)

True

## 3) control de fluxo: `if`, `for`, `while`
Obxectivo: tomar decisións e repetir accións.

**exercicio 3.1 — cualificación dunha nota**

Escribe un `if/elif/else` que, dada a variable `nota` (float de 0 a 10), asigne en `cual` unha cadea: `'sobresaínte'` (>=9), `'notable'` (>=7), `'aprobado'` (>=5), `'suspenso'` (resto). Proba con 7.3.

In [8]:
nota = 7
if (nota >= 9):
    cual = "sobresaínte"
elif (nota >= 7):
    cual = "notable"
elif (nota >= 5):
    cual = "suficiente"
else:
    cual = "suspenso"

print(f"nota = {nota}; cual = {cual}")

nota = 7; cual = notable


**exercicio 3.2 — suma con `for`**

Usa un bucle `for` con `range(1, 6)` para sumar os números do 1 ao 5 (incluídos).

In [16]:
res = 0
for i in range(1,6):
    res += i
print (res)

15


**exercicio 3.3 — bucle `while`**

Comeza con `cont = 3`. Mentres `cont > 0`, réstalle 1. Mostra o resultado final.

In [19]:
cont = 3
while cont  > 0:
    cont-=1

print(cont)

0


**exercicio 3.4 — múltiplos de 3 e 5**

Conta cantos números entre 1 e 100 son múltiplos **á vez** de 3 e 5.

In [20]:
num_multiplos = 0
for i in range (1,101) :
    if (i % 5 == 0 and i % 3 == 0):
        num_multiplos += 1

print(f"num_multiplos: {num_multiplos}")


num_multiplos: 6


## 4) estruturas de datos: lista, tupla, set, dict
Obxectivo: crear e manipular coleccións.

**exercicio 4.1 — lista**

Crea a lista `nums = [1, 2, 3]`, engade o número `4` e comproba o primeiro, o último e a lonxitude.

In [26]:
nums = [1,2,3]
nums.append(4)

print(nums[0])
print(len(nums))
print(nums[-1])
print(nums)

1
4
4
[1, 2, 3, 4]


**exercicio 4.2 — tupla**

Crea a tupla `punto = (3, 4)` e mostra as súas dúas compoñentes.

In [ ]:
punto = (3,4)
punto[0],punto[1]


(3, 4)

**exercicio 4.3 — conxunto (set)**

Dado `{1, 2, 2, 3}`, comproba a pertenza de `2` e observa que os duplicados desaparecen.

In [30]:
conx = {1,2,2,3,4}
num = 0

if (num in conx):
    print(f"{num} pertence a {conx}")

**exercicio 4.4 — dicionario**

Crea o dicionario `alum = {'nome': 'Iria', 'idade': 17}` e recupera `'idade'`. Usa `get` para unha clave inexistente con valor por defecto `'descoñecido'`.

In [37]:
alum = {'nome':'Iria', 'idade':17}
#alum['idade']

alum.get('idade','descoñecido')


17

**exercicio 4.5 — comprensións**

Usa comprensións para:
1) crear unha lista chamada `cadrados` que conteña os cadrados do 0 ao 9 (`range(10)`).
2) crear un dicionario chamado `ascii_letras` no que as claves son cada unha das letras e o valor a súa posición no código ascii (`ord(letra)`).

In [42]:
cadrados = [i*i for i in range(6)]

print(cadrados)

letras = {letra: ord(letra) for letra in 'abcefghijklmnopqrstuvwxyz'}
print(letras)


[0, 1, 4, 9, 16, 25]
{'a': 97, 'b': 98, 'c': 99, 'e': 101, 'f': 102, 'g': 103, 'h': 104, 'i': 105, 'j': 106, 'k': 107, 'l': 108, 'm': 109, 'n': 110, 'o': 111, 'p': 112, 'q': 113, 'r': 114, 's': 115, 't': 116, 'u': 117, 'v': 118, 'w': 119, 'x': 120, 'y': 121, 'z': 122}


**exercicio 4.6 — únicos e cadrados**

Dada `datos = [1,2,2,3,4,4,5]`, obtén o conxunto de únicos e crea un dict que mapee cada valor ao seu cadrado.

In [45]:
# código do alumnado
datos = [1,2,2,3,4,4,5]
unicos = set(datos)
mapeo = {i: i*i for i in unicos}

unicos, mapeo

({1, 2, 3, 4, 5}, {1: 1, 2: 4, 3: 9, 4: 16, 5: 25})

## 5) funcións
Obxectivo: definir funcións con argumentos, valores por defecto, *args/**kwargs e lambda.

**exercicio 5.1 — área dun rectángulo**

Define `area_rect(a: float, b: float = 1.0) -> float` que devolva `a*b`. Proba `area_rect(3,4)` e `area_rect(5)`.

In [47]:
# código do alumnado
def area (a: float, b: float = 1.0):
    return a*b

area(3,4), area(5)

(12, 5.0)

**exercicio 5.2 — *args**

Escribe `sumar_todo(*args)` que devolva a suma de todos os argumentos.

In [50]:
def sumar_todo (*args):
    res = 0
    for a in args:
        res+=a
    return res
sumar_todo(1,2,3,4,5,6)

21

**exercicio 5.3 — **kwargs**
Imos usar `kwargs`para:
- a función `demo_kwargs(**kwargs)` que devolva directamente `kwargs`. Proba con `nome='Iria', idade=17`.
- a función `saudar(**kwargs)` que recibe un número variable de parámetros. Entre eles:
  - `nome`: por defecto 'descoñecido'.
  - `apelidos`: por defecto ''.
  - `idioma`: pode ser `es`|`gl`|`en`, por defecto `gl`.
  
  O programa debe saudar, mencionando nome e apelidos, no idioma indicado. 

In [53]:
# código do alumnado
def demo_kwargs(**kwargs):
    return kwargs
demo_kwargs(nome='Iria', idade=17)

def saudar(**kwargs):
    nome = kwargs.get('nome')
    apelidos = kwargs.get('apelidos','')
    idioma = kwargs.get('idioma','gl')

    if (idioma == 'gl'):
        return f"Ola, {nome} {apelidos}!"
    else:
        if (idioma == 'es'):
            return f"Hola, {nome} {apelidos}!"
        else:
            if (idioma == 'en'):
                return f"Hello, {nome} {apelidos}"
            else:
                return "Idioma non dispoñible"

saudar(nome='Adri',apelidos='Blanco', idioma='pt')        

'Idioma non dispoñible'

**exercicio 5.4 — media segura**

Escribe `media(lista)` que devolva a media dunha lista de números, devolvendo `None` se a lista está baleira.

In [54]:
# código do alumnado
# from typing import Optional, Sequence
# def media(lista: Sequence[float]) -> Optional[float]:
#     ...
# media([1,2,3]), media([])

def media (lista):
    if (len(lista)== 0):
        return None
    total = 0
    for i in lista:
        total+=i
    return total/len(lista)

media([1,2,3,4]), media([])

(2.5, None)

**exercicio 5.5 — lambda par**

Crea unha función lambda `par` que devolva `True` se o número é par.

In [55]:
# código do alumnado
# par = lambda x: ...
# par(6), par(7)

par = lambda x: x % 2 == 0
par(2),par(7)

(True, False)

## 6) clases e obxectos
Obxectivo: crear clases simples, métodos e herdanza.

**exercicio 6.1 — clase Punto**

Crea unha clase `Punto` con `x` e `y`. Engade:
- método `desprazar(dx, dy)`
- método `modulo()` que devolva a distancia á orixe. Módulo = sqrt(x² + y²)
- `__repr__` amigable
Proba con `Punto(3,4)` e despraza (-1,2).


In [58]:
class Punto:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def desprazar(self, dx, dy):
        self.x+=dx
        self.y+=dy
    def modulo(self):
        return (self.x**2 + self.y**2)**0.5
    
    def __repr__(self):
        return f"Punto({self.x},{self.y})"
#         ...
#     def modulo(self):
#         ...
#     def __repr__(self):
#         ...
p = Punto(3,4)
p.modulo()
p.desprazar(-1,2)
p

Punto(2,6)

**exercicio 6.2 — herdar Punto3D**

Crea `Punto3D(Punto)` engadindo `z` e redefinindo `modulo()` para 3D. Proba con `(1,2,2)`. Módulo = sqrt(x² + y² + z²)

In [62]:
# código do alumnado
# class Punto3D(Punto):
#     def __init__(self, x,y,z):
#         ...
#     def modulo(self):
#         ...
# p3 = Punto3D(1,2,2)
# p3, p3.modulo()

class Punto3D(Punto):
    def __init__(self,x,y,z):
        super().__init__(x,y)
        self.z = z
    
    def modulo(self):
        return (self.x**2 + self.y**2 + self.y**2)**0.5
    
p3d = Punto3D(1,2,2)

p3d.modulo()
        



3.0

**exercicio 6.3 — clase Alumno**

Crea `Alumno` con `nome` e `notas` (lista). Engade:
- `engadir(nota)`
- `media()` (ou `None` se baleira)
- `__repr__`
Proba con `Iria` e notas `[7,8,9]`.

In [6]:
class Alumno:
    def __init__(self, nome, notas=None):
        self.nome = nome
        if (notas == None):
            self.notas=[]
        else:
            self.notas = notas
    
    def engadir(self, nota):
        self.notas.append(nota)

    def media (self):
        acc = 0
        for nota in self.notas:
            acc += nota
        return acc/len(self.notas)
    
    def __repr__(self):
        return f"Notas de {self.nome} : {self.notas}. Media: {self.media():.2f}"
    
a = Alumno('Iria',[6,3])
a.engadir(8)
print(a)

Notas de Iria : [6, 3, 8]. Media: 5.67


## 7) operacións con strings
Obxectivo: dominar métodos comúns e f-strings.

**exercicio 7.1 — limpeza e transformación**

Dada `s = '  ola, mundo!  '`, obtén:
- Quita os epazos nos extremos (`strip()`)
- Pásaa a maiúsculas (`upper()`)
- substitúe `'mundo'` por `'python'` (`replace`)
- Divídea en strings diferentes polo símbolo `,` (`split()`)
- Volve a xuntar as strings co separador '->' (`join`).

In [75]:
s = ' ola, mundo! '
s = s.strip()
s.upper()
s.replace('mundo','python')
a, b = s.split(',')
a,b
'->'.join([a,b])

'ola-> mundo!'

**exercicio 7.2 — f-strings**

Con `nome='Iria'` e `nota=8.75`, constrúe a mensaxe: `'Iria ten un 8.8'` usando f-strings e formato `:.1f`.

In [77]:
# código do alumnado
nome, nota = 'Iria', 8.75
print (f"{nome} ten un {nota:.2f}")

Iria ten un 8.75


**exercicio 7.3 — análise de texto**

Dado `'Python é incríbel'`, devolve a versión en minúsculas, o número de letras `'e'` e a frase co texto `'incríbel'` substituído por `'divertido'`.

In [ ]:
# código do alumnado
# texto = 'Python é incríbel'
# texto.lower(), texto.count('e'), texto.replace('incríbel','divertido')

## 8) introdución a numpy
Obxectivo: crear e manipular arrays; estatística simple.

**exercicio 8.1 — creación e formas**

Crea os seguintes elementos:
- Un array de `numpy` a partir da lista `[1,2,3,4)` 
- Unha matriz de 3x3 a partir dun array do 1 ao 10 (crear con `arange` e convertir en matriz con `reshape`). 

In [80]:
# código do alumnado
import numpy as np
arr = np.array([1,2,3,4])
arr
mat = np.arange(1,10).reshape(3,3)
mat
# mat = np.arange(1,10).reshape(3,3)
# arr, mat, arr.dtype, mat.shape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**exercicio 8.2 — slicing e broadcasting**

A partir da matriz do exercicio anterior, obtén:
- a **primeira columna** da matriz.
- a **primeira fila** da matriz.
- crea unha nova matriz **sumado 10** a todos os elementos.
- crea unha nova matriz **multiplicando por 2** todos os elementos.

In [89]:
# código do alumnado
# mat[:, 0], mat[0, :], mat + 10, mat * 2
mat[:,0], mat[0,:], mat+10, mat*2


(array([1, 4, 7]),
 array([1, 2, 3]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [ ]:
# código do alumnado
# mat.sum(), mat.mean(), mat.max(), mat @ np.ones((3,1))

**exercicio 8.4 — diagonal e filtrado**

Fai o seguinte:
- Crea unha matriz 4x4 cos números do 0 ao 15
- Extrae a diagonal principal 
- Crea un array cos elementos pares
- Calcula a media dos elementos > 7.

In [88]:
# código do alumnado
# m = np.arange(16).reshape(4,4)
# diag = np.diag(m)
# media_maiores7 = m[m > 7].mean()
# m, diag, media_maiores7

m = np.arange(16).reshape(4,4)
diag = np.diag(m)
pares = m[m%2==0]
media_m7 = m[m>7].mean()
m,diag, pares, media_m7

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([ 0,  5, 10, 15]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14]),
 11.5)